# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-08 08:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Excercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reps', models.PositiveIntegerField()),
                ('sets', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('desc', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('length', models.PositiveIntegerField()),
                ('desc', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(default='<django.db.models.fields.related.ForeignKey> [<django.db.models.fields.PositiveIntegerField>]', max_length=100)),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routines.Routine')),
            ],
        ),
        migrations.AddField(
            model_name='excercise',
            name='excercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routines.Movement'),
        ),
        migrations.AddField(
            model_name='excercise',
            name='workout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routines.Workout'),
        ),
    ]
