# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-08 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='excercise',
            name='order',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workout',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
