# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-11 06:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0003_auto_20170709_1640'),
    ]

    operations = [
        migrations.RenameField(
            model_name='excercise',
            old_name='excercise',
            new_name='name',
        ),
    ]
