# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-29 11:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0005_routine_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routine',
            name='num_days',
        ),
    ]
